---
- name: "Apache installation using Docker on DEBIAN Ubuntu"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: vagrant
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Install prerequisites for Docker
      package:
        name:
          - docker.io
          - python3
          - python3-pip            
        state: present

    - name: Install Docker module for Python
      pip:
        name: docker
        executable: pip3

  tasks:
    - name: Create Apache container using Docker
      community.docker.docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
