---
- name: Template index.html-easter_egg.j2 to index.html on target
  template:
    src: index.html-easter_egg.j2
    dest: "{%- if ansible_distribution == 'CentOS' -%}/usr/share/nginx/html{%- elif ansible_distribution == 'Ubuntu' -%}/var/www/html{%- endif %}/index.html"
    mode: 0644

- name: Install unzip
  package:
    name: unzip
    state: latest

- name: Unarchive playbook stacker game
  unarchive:
    src: playbook_stacker.zip
    dest: "{%- if ansible_distribution == 'CentOS' -%}/usr/share/nginx/html{%- elif ansible_distribution == 'Ubuntu' -%}/var/www/html{%- endif %}"
    mode: 0755