---
- name: Install Python 3 and pip3
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Docker module for Python
  pip:
    name: docker
    executable: pip3
    
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Enable and Start docker
  service:
    name: docker
    state: started
    enabled: yes